### PR TITLE
Various improvements and customization

### PR DESCRIPTION
**Pull request by lucventurini**
Changes:
- Now RaGOO can specify the output folder (`-o`)
- It is now possible to specify a minimum alignment quality (`-q`) as well as pass the `-I` parameter to minimap2, plus other various parameters (e.g. `-x`)
- Using PySam and `re` for retrieving sequences and printing out the final pseudomolecules. Orders of magnitudes faster and lighter on memory or disk.
- RaGOO will now print out a sentinel file in the `orderings` folder to avoid redoing the calculations.
- Printing out the `groupings` and `orderings` folders now takes orders of magnitude less time: on wheat, the whole process (reading the alignments, grouping and ordering) now takes ~2 minutes, instead of one hour.
- Now the `orderings` files contain also the inferred location of the assigned scaffolds. This will help to ascertain the correctness of the mappings.
- Created an `environment.yml` file to create the right `conda` environment for using RaGOO.

Other improvements to come soon.

### CODE REVIEW

**Comment by malonge** [comment]
Hi there,

I recently finished a big project and I am now looking to write version 2 of RaGOO. I am going to make some pretty dramatic changes to incorporate some new features and code improvements that you and others have brought up. I also plan to use some of your enhancements like speeding up fasta IO with pysam. I will be sure to give you credit for improvements inspired by your work.

So I wanted to let you know that I am now working on this in case you are still working on this branch. My hope is to have this ready by the end of summer. Thanks so much for all of the help.

**Comment by lucventurini** [comment]
Dear @malonge,

> I recently finished a big project and I am now looking to write version 2 of RaGOO. I am going to make some pretty dramatic changes to incorporate some new features and code improvements that you and others have brought up. I also plan to use some of your enhancements like speeding up fasta IO with pysam. I will be sure to give you credit for improvements inspired by your work.

That's great news! And thank you for the acknowledgement, much appreciated.

> So I wanted to let you know that I am now working on this in case you are still working on this branch. My hope is to have this ready by the end of summer. Thanks so much for all of the help.

I am currently working a lot on other projects, so I have not had much time to continue on this in the past three months. But if you need help or testing, please let me know, I will try to fit in our schedule.

**Comment by malonge** [comment]
Thanks for your willingness to collaborate. I have a few questions about your file IO if you don't mind since this is a super important optimization.

For reading fasta files, I see that you use `pysam.FastaFile`. This does make it quite a big faster, but I assume this means that gzip input is not allowed. Is that right? If so I think I will take that trade-off. 

For writing fasta files, I see that you used `pysam.BGZFile`. You also used `re` to wrap lines and you buffered the file writing. In your testing, did this technique save a lot of time or was it primarily used to lower the disk/memory footprint?

**Comment by lucventurini** [comment]
> For reading fasta files, I see that you use pysam.FastaFile. This does make it quite a big faster, but I assume this means that gzip input is not allowed. Is that right? If so I think I will take that trade-off.

BGZip is fine, simple gzip is not. 

> For writing fasta files, I see that you used pysam.BGZFile. You also used re to wrap lines and you buffered the file writing. In your testing, did this technique save a lot of time or was it primarily used to lower the disk/memory footprint? 

If memory serves, the buffering and use of `re` provided a significant speedup as well as lower memory footprint.

**Pull request closed without merging**
